### ISSUE TITLE
No req.gql.g.dart generated

### ISSUE THREAD

**Issue by michaelspeed** [gql-dart/ferry#159]
With using flutter 2.0.1 no `.g.dart` files are generated

the generated files look like this

![Screenshot at Mar 18 00-53-24](https://user-images.githubusercontent.com/1447958/111526150-62536f00-8784-11eb-9fc5-90b04ab7352e.png)

and inside the Mutation.req.gql.dart I have this error 

![Screenshot at Mar 18 00-54-21](https://user-images.githubusercontent.com/1447958/111526301-9333a400-8784-11eb-8171-106e9cf5872a.png)

pubspec - 

```
version: 1.0.0+1

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts:
  ferry: ^0.9.4
  ferry_flutter:
  gql_http_link:
  hive:
  ferry_hive_store:
  getwidget: ^1.2.4
  flutter_icons:
  hive_flutter:

dev_dependencies:
  flutter_test:
    sdk: flutter
  ferry_generator:
  build_runner:
  gql_build:
  gql_code_builder:

dependency_overrides:
  analyzer: '0.41.1'
```
