### ISSUE TITLE
`bigint` not de-serialize properly

### ISSUE THREAD

**Issue by anthonychwong** [gql-dart/ferry#160]
> Deserializing '1' to 'Gbigint' failed due to: Expected a value of type 'String', but got one of type 'int'

Hi, I work with GraphQL with `bigint` fields. When I run the query, the response comes with above link error.

**Comment by smkhalsa** [comment]
bigint is not a native graphql scalar. 

If you wish to parse it into a dart int, you'll need to follow the docs for setting up a custom scalar.

**Comment by anthonychwong** [comment]
Thanks, I want to use BigInt in dart for bigint in graphql field, so I update the `build.yaml` accordingly.

The request builder looks good.

```dart
  final req = GStuff_by_tagsReq(
    (b) => b
      ..vars.tag_ids = ListBuilder([BigInt.one])
  );
```

However, I still get similar exception for response.

> Deserializing '1' to 'BigInt' failed due to: Expected a value of type 'String', but got one of type 'int'

```yaml
targets:
  $default:
    builders:
      gql_build|ast_builder:
        enabled: true
      gql_build|schema_builder:
        enabled: true
        options:
          type_overrides:
            bigint:
              name: BigInt
      gql_build|data_builder:
        enabled: true
        options:
          schema: my_package_name|lib/schema.graphql
          type_overrides:
            bigint:
              name: BigInt
      gql_build|var_builder:
        enabled: true
        options:
          schema: my_package_name|lib/schema.graphql
          type_overrides:
            bigint:
              name: BigInt
      gql_build|serializer_builder:
        enabled: true
        options:
          schema: my_package_name|lib/schema.graphql
          custom_serializers:
            - import: 'package:built_value/src/big_int_serializer.dart'
              name: BigIntSerializer
      ferry_generator|req_builder:
        enabled: true
        options:
          schema: my_package_name|lib/schema.graphql
          type_overrides:
            bigint:
              name: BigInt
```
