### ISSUE TITLE
[Help / Resource] Building queries with custom scalars?

### ISSUE THREAD

**Issue by antholeole** [gql-dart/ferry#167]
Hi there! I'm looking for examples on building queries with custom scalars. Currently, I have a custom UuidType called `UuidType` that looks like this (assertions omitted for brevity):

```
class UuidType {
  late String _uuid;

  UuidType(String uuid) {
    _uuid = uuid;
  }

  String get uuid => _uuid;
}
```

here's my type serializer (if it matters... I'm not really sure)

```
class UuidTypeSerializer implements PrimitiveSerializer<UuidType> {
  @override
  UuidType deserialize(
    Serializers serializers,
    Object serialized, {
    FullType specifiedType = FullType.unspecified,
  }) {
    assert(serialized is String,
        "UuidTypeSerializer expected 'String' but got ${serialized.runtimeType}");
    return UuidType(serialized as String);
  }

  @override
  Object serialize(
    Serializers serializers,
    UuidType uuidType, {
    FullType specifiedType = FullType.unspecified,
  }) =>
      uuidType.uuid;

  @override
  Iterable<Type> get types => [UuidType];

  @override
  String get wireName => 'uuid';
}
```

and I have my `build.yaml`:

```
targets:
  $default:
    builders:
      gql_build|schema_builder:
        enabled: true
        options:
          type_override:
              uuid:
                  name: UuidType
                  import: 'package:fe/helpers/uuid_type.dart'
      gql_build|ast_builder:
        enabled: true
      gql_build|data_builder:
        enabled: true
        options:
          schema: fe|lib/gql/schema.graphql
          type_override:
              uuid:
                  name: UuidType
                  import: 'package:fe/helpers/uuid_type.dart'
      gql_build|var_builder:
        enabled: true
        options:
          schema: fe|lib/gql/schema.graphql
          type_override:
              uuid:
                  name: UuidType
                  import: 'package:fe/helpers/uuid_type.dart'
      gql_build|serializer_builder:
        enabled: true
        options:
          schema: fe|lib/gql/schema.graphql
          custom_serializers:
          - import: 'package:fe/helpers/uuid_type.dart'
            name: UuidTypeSerializer
      ferry_generator|req_builder:
        enabled: true
        options:
          schema: fe|lib/gql/schema.graphql
          type_override:
              uuid:
                  name: UuidType
                  import: 'package:fe/helpers/uuid_type.dart'
```

but when I try to build a query using a `UuidType` userId, it expects a GuuidBuilder instead of a UuidType. I'm trying to do the following: 

```
    final q = GGetSelfGroupsReq(
      (b) => b..vars.self_id = self_id
    );
```
but it errors with `A value of type 'UuidType' can't be assigned to a variable of type 'GuuidBuilder?'. Try changing the type of the variable, or casting the right-hand type to 'GuuidBuilder?'`. I'm not familiar with the built_values package, but I went ahead and looked at the GuuidBuilder constructor and it seems to not take any values at all.

How do I make a query using a Uuid?

Thanks for the help and the awesome package - I'm sure I'm missing something. It would be helpful to have examples of a custom scalar type.

Other info:

- my query:
```
query GetSelfGroups($self_id: uuid!) {
 	 user_to_groups(where: {
    user_id: {
    	_eq: $self_id
    }
  }) {
   	group {
      group_name
    }
  }
}
```
- Flutter sdk version >=2.12.0 < 3
- ferry: ^0.10.1-0.1.nullsafety.0
