### ISSUE TITLE
Generated code for input type keyword "update" clashes with Builder method "update"

### ISSUE THREAD

**Issue by kierien** [gql-dart/ferry#169]
Thanks for all the work on ferry!

I've come across an issue whereby the generator generates invalid code when there is a GraphqQL input type with the keyword "update". The generated code includes a getter/setter called "update" that clashes with an internal method from Builder with the same name. 

![screenshot](https://user-images.githubusercontent.com/60668038/113515624-391a4780-95a8-11eb-94ac-3379018559fb.png)

I understand ferry tries to escape any internal keywords by adding "g" in front, could probably do the same here.

**Comment by michaelspeed** [comment]
did you find any solution for this?

**Comment by boosey** [comment]
Running into the same problem. 

pubspec:
```
environment:
  sdk: ">=2.7.0 <3.0.0"

dependency_overrides:
  analyzer: ^0.41.2
  dart_style: 1.3.13


dependencies:
  gql_link: ^0.3.1
  gql_http_link: ^0.3.2
  ferry: ^0.9.4
  ferry_flutter: ^0.4.0
  get_it: ^6.0.0

dev_dependencies:
  flutter:
    sdk: flutter
  build_runner: 1.10.1
  gql_build: ^0.1.4+2
  gql_code_builder: ^0.1.4+1
  ferry_generator: ^0.3.3
```
VS Code Problem Tab:
<img width="1254" alt="Screen Shot 2021-04-11 at 11 02 08 AM" src="https://user-images.githubusercontent.com/2569582/114311714-735a7c00-9ab5-11eb-8262-dd1009f56766.png">

<img width="1249" alt="Screen Shot 2021-04-11 at 11 04 06 AM" src="https://user-images.githubusercontent.com/2569582/114311778-b4529080-9ab5-11eb-999d-f01059677e4a.png">


There are also 30+ warning about camel case style violations.

Is there a work around? Is there a ETA on a fix?
