### ISSUE TITLE
Serializer.gql.g.dart not importing type correctly

### ISSUE THREAD

**Issue by antholeole** [gql-dart/ferry#176]
Hi there! Thanks for the wonderful package and brisk update to NNBD.

I currently have a `build.yaml` that specifies a custom type, `UuidType`. Everything works well besides the generated serializer imports the serializer, but not the actual type.

Here's the offending code:

NOTE: The error is something like "UuidType is not defined." I can get exact error message if needed but I don't think it's necessary.

in `serializers.gql.g.dart`:
```dart
..addBuilderFactory(
          const FullType(BuiltList, const [const FullType(UuidType)]),
          () => new ListBuilder<UuidType>())
      ..addBuilderFactory(
          const FullType(BuiltList, const [const FullType(UuidType)]),
          () => new ListBuilder<UuidType>())
```

the build.yaml serializer section:

(NOTE: I've tried with and without the `type_overrides` section.

```yaml
      gql_build|serializer_builder:
        enabled: true
        options:
          schema: fe|lib/gql/schema.graphql
          custom_serializers:
          - import: 'package:fe/stdlib/helpers/uuid_type.dart'
            name: UuidTypeSerializer
          type_overrides:
          - import: 'package:fe/stdlib/helpers/uuid_type.dart'
            name: UuidType
``` 

the import that IS being generated: 

```dart 
import 'package:fe/stdlib/helpers/uuid_type.dart' show UuidTypeSerializer;
```

the fix that I manually enter every time:

```dart
import 'package:fe/stdlib/helpers/uuid_type.dart' show UuidType, UuidTypeSerializer;
```

I defined my serializer and the data structure in the same file.

Thanks!

**Comment by smkhalsa** [comment]
As [shown in the docs](https://ferrygraphql.com/docs/custom-scalars#complete-buildyaml-example), the `type_overrides` should be defined in all of the builders other than the `serializer_builder`

**Comment by antholeole** [comment]
Sorry, must have missed your comment notification.

I do have `type_overrides` defined in all of the builders - here's the full `build.yaml`:

```yaml
targets:
  $default:
    builders:
      gql_build|ast_builder:
        enabled: true
      gql_build|schema_builder:
        enabled: true
        options:
          schema: fe|lib/gql/schema.graphql
          type_overrides:
              uuid:
                  name: UuidType
                  import: 'package:fe/stdlib/helpers/uuid_type.dart'
      gql_build|data_builder:
        enabled: true
        options:
          schema: fe|lib/gql/schema.graphql
          type_overrides:
              uuid:
                  name: UuidType
                  import: 'package:fe/stdlib/helpers/uuid_type.dart'
      gql_build|var_builder:
        enabled: true
        options:
          schema: fe|lib/gql/schema.graphql
          type_overrides:
              uuid:
                  name: UuidType
                  import: 'package:fe/stdlib/helpers/uuid_type.dart'
      gql_build|serializer_builder:
        enabled: true
        options:
          schema: fe|lib/gql/schema.graphql
          custom_serializers:
          - import: 'package:fe/stdlib/helpers/uuid_type.dart'
            name: UuidTypeSerializer
          type_overrides:
          - import: 'package:fe/stdlib/helpers/uuid_type.dart'
            name: UuidType

      ferry_generator|req_builder:
        enabled: true
        options:
          schema: fe|lib/gql/schema.graphql
          type_overrides:
            uuid:
              name: UuidType
              import: 'package:fe/stdlib/helpers/uuid_type.dart'
```

**Comment by antholeole** [comment]
closed - got it to work with after some tinkering - leaving this here as an example if someone runs across the same issue:

```yaml
targets:
  $default:
    builders:
      gql_build|ast_builder:
        enabled: true
      gql_build|schema_builder:
        enabled: true
        options:
          schema: fe|lib/gql/schema.graphql
          type_overrides:
              uuid:
                  name: UuidType
                  import: 'package:fe/stdlib/helpers/uuid_type.dart'
      gql_build|data_builder:
        enabled: true
        options:
          schema: fe|lib/gql/schema.graphql
          type_overrides:
              uuid:
                  name: UuidType
                  import: 'package:fe/stdlib/helpers/uuid_type.dart'
      gql_build|var_builder:
        enabled: true
        options:
          schema: fe|lib/gql/schema.graphql
          type_overrides:
              uuid:
                  name: UuidType
                  import: 'package:fe/stdlib/helpers/uuid_type.dart'
      gql_build|serializer_builder:
        enabled: true
        options:
          schema: fe|lib/gql/schema.graphql
          custom_serializers:
          - import: 'package:fe/stdlib/helpers/uuid_type.dart'
            name: UuidTypeSerializer
          type_overrides:
            uuid:
              import: 'package:fe/stdlib/helpers/uuid_type.dart'
              name: UuidType
      ferry_generator|req_builder:
        enabled: true
        options:
          schema: fe|lib/gql/schema.graphql
          type_overrides:
            uuid:
              name: UuidType
              import: 'package:fe/stdlib/helpers/uuid_type.dart'
```

thanks for the awesome package, @smkhalsa! Makes working with Gql in Flutter a breeze :)
