### ISSUE TITLE
No .req. file and request Classes generated

### ISSUE THREAD

**Issue by d-polikhranidi** [gql-dart/ferry#207]
Hello everyone!

Can't put my finger on what is problem with my GraphQL schema ([user.txt](https://github.com/gql-dart/ferry/files/6664705/user.txt)). Ferry-generator doesn't generate .req. file and I can't make any requests to my endpoint cause there's no request Classes.

On endpoint's playground I can make all requests and gain data.
Backend is a bundle of **mongoose+graphql-compose+apollo-server.**

**Example of requests in schema:**

```
type Mutation {
  userRegister(email: String!, password: String!, name: String!, roles: [String!]): User

  """
  Update one document: 1) Retrieve one document by findById. 2) Apply updates to
  mongoose document. 3) Mongoose applies defaults, setters, hooks and
  validation. 4) And save it.
  """
  userUpdateById(_id: MongoID!, record: UpdateByIdUserInput!): UpdateByIdUserPayload

  """
  Remove one document: 1) Retrieve one document and remove with hooks via findByIdAndRemove. 2) Return removed document.
  """
  userRemoveById(_id: MongoID!): RemoveByIdUserPayload
}
```

I see that my schema is not similar to the one in the examples, but I can't understand what I'm doing wrong :(

My **build.yaml**:

```
targets:
  $default:
    builders:
      gql_build|schema_builder:
        enabled: true
      gql_build|ast_builder:
        enabled: true
      gql_build|data_builder:
        enabled: true
        options:
          schema: awesome_app|lib/graphql/user.graphql
      gql_build|var_builder:
        enabled: true
        options:
          schema: awesome_app|lib/graphql/user.graphql
      gql_build|serializer_builder:
        enabled: true
        options:
          schema: awesome_app|lib/graphql/user.graphql

      ferry_generator|req_builder:
        enabled: true
        options:
          schema: awesome_app|lib/graphql/user.graphql
```

**flutter pub run build_runner build** output:

```
[INFO] Generating build script...
[INFO] Generating build script completed, took 578ms

[INFO] Precompiling build script......
[INFO] Precompiling build script... completed, took 8.4s

[INFO] Initializing inputs
[INFO] Building new asset graph...
[INFO] Building new asset graph completed, took 735ms

[INFO] Checking for unexpected pre-existing outputs....
[INFO] Checking for unexpected pre-existing outputs. completed, took 1ms

[INFO] Running build...
[INFO] 1.1s elapsed, 4/5 actions completed.
[INFO] 2.6s elapsed, 4/5 actions completed.
[INFO] 3.7s elapsed, 6/15 actions completed.
[INFO] 4.8s elapsed, 7/15 actions completed.
[INFO] 5.9s elapsed, 7/15 actions completed.
[INFO] 7.0s elapsed, 7/15 actions completed.
[INFO] 15.8s elapsed, 7/15 actions completed.
[INFO] Running build completed, took 16.7s

[INFO] Caching finalized dependency graph...
[INFO] Caching finalized dependency graph completed, took 43ms

[INFO] Succeeded after 16.7s with 7 outputs (29 actions)
```

**Generated files:**

![build_runner_generated_files](https://user-images.githubusercontent.com/76728763/122266028-0367d800-cee2-11eb-8416-e4195ca5367f.png)

**flutter doctor -v** output:

```
[✓] Flutter (Channel stable, 2.2.1, on macOS 11.4 20F71 darwin-x64, locale ru-BY)
    • Flutter version 2.2.1 at /Users/admin/nextgen/flutter
    • Framework revision 02c026b03c (3 weeks ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/admin/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.57.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.23.0

[✓] Connected device (2 available)
    • iPhone (mobile) • 00008030-00125C940292802E • ios            • iOS 14.6
    • Chrome (web)    • chrome                    • web-javascript • Google Chrome 91.0.4472.106
    ! Error: iPhone is busy: Copying cache files from device. Xcode will continue when iPhone is finished. (code -10)

• No issues found!
```

Will appreciate for any help!
