### ISSUE TITLE
Schema with custom scalar list not resolved correctly by Ferry

### ISSUE THREAD

**Issue by hazzo** [gql-dart/ferry#235]
Hi I was trying to make a serializer for a custom Scalar (Upload) and I realized that if a mutation has a property containing a list of this custom scalar Ferry will not generate correctly the `serializers.gql.g.dart` file. It's there a bug or I'm doing something wrong?

Example:

```graphql
input MutationInput {
  text: String!
  images: [Upload]
  clientMutationId: String
}
```

```yaml
      gql_build|schema_builder:
        enabled: true
        options:
          schema: app_name|lib/common/data/graphql/schema.graphql
          type_overrides:
            Upload:
              name: MultipartFile
              import: 'package:http/http.dart'
```

```yaml
      gql_build|serializer_builder:
        enabled: true
        options:
          schema: app_name|lib/common/data/graphql/schema.graphql
          custom_serializers:
            - import: 'package:app_name/common/data/serializers/upload_serializer.dart'
              name: UploadSerializer
```

This generates the following error in the generated file:

![Screenshot 2021-08-04 at 13 53 01](https://user-images.githubusercontent.com/13692810/128176332-f1307491-19aa-4a95-bb66-d308f1053152.png)

If I remove the list in the `schema.grahpql` like this, Ferry compiles and generates the files correctly without the above error.

```graphql
input MutationInput {
  text: String!
  images: Upload
  clientMutationId: String
}
```

If you need more info let me know. Thanks!
