### ISSUE TITLE
'List<Object?>' is not a subtype of type 'String?'

### ISSUE THREAD

**Issue by samderlust** [gql-dart/ferry#247]
Hi,
I'm having an issue with deserialization that says `'List<Object?>' is not a subtype of type 'String?'`
I'm using Django in the backend with Django GraphQL Auth. The response for logging in is ok if I put in the correct username and password. But when I put the wrong credentials. The response can't be deserialized 

This is the response from grapql
```
{
  "data": {
    "tokenAuth": {
      "success": false,
      "errors": {
        "nonFieldErrors": [
          {
            "message": "Please, enter valid credentials.",
            "code": "invalid_credentials"
          }
        ]
      },
      "token": null,
      "refreshToken": null,
      "unarchiving": false,
      "user": null
    }
  }
}
```
This is the error output:
```
LinkException(Deserializing '[__typename, Mutation, tokenAuth, {__typename: ObtainJSONWebToken, token: nul...' to 'GtokenAuthData' failed due to: Deserializing '[__typename, ObtainJSONWebToken, success, false, errors, {nonFieldErrors: [{m...' to 'GtokenAuthData_tokenAuth' failed due to: Deserializing '[nonFieldErrors, [{message: Please, enter valid credentials., code: invalid_c...' to 'GExpectedErrorType' failed due to: type 'List<Object?>' is not a subtype of type 'String?' in type cast)
```

pubspec.yaml
```

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cached_network_image: ^3.1.0
  camera: ^0.9.0
  corsac_jwt: ^1.0.0-nullsafety.1
  date_time_picker: ^2.1.0
  email_validator: ^2.0.1
  equatable: ^2.0.3
  faker: ^2.0.0
  ferry: ^0.10.4
  firebase_core: ^1.5.0
  firebase_dynamic_links: ^2.0.8
  flutter:
    sdk: flutter
  flutter_calendar_carousel: ^2.0.3
  flutter_chat_bubble: ^2.0.0
  flutter_dotenv: ^5.0.2
  flutter_form_bloc: ^0.20.1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^1.2.1
  flutter_riverpod: ^1.0.0-dev.7
  flutter_secure_storage: ^4.2.1
  flutter_translate: ^3.0.1
  freezed_annotation: ^0.14.1
  gql: ^0.13.0
  gql_http_link: ^0.4.0
  http: ^0.13.3
  image_picker: ^0.8.3+3
  intercom_flutter: ^5.0.2
  logger: ^1.1.0
  mask_text_input_formatter: ^2.0.0
  phone_number: ^0.12.0
  shared_preferences: ^2.0.7
  timeago: ^3.1.0
  uploadcare_flutter: ^1.0.2
  video_player: ^2.1.14
  webview_flutter: ^2.0.12

#  cupertino_icons: ^1.0.2
dev_dependencies:
  build_runner: ^2.1.1
  ferry_generator: ^0.4.4
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter
  freezed: ^0.14.0

```
