### ISSUE TITLE
Enum not being created

### ISSUE THREAD

**Issue by j-waters** [gql-dart/ferry#264]
I have the following fragment:

```graphql
fragment FileFragment on File {
    name, path, type
}
```

which uses the schema

```graphql
...

type File {
  path: String!
  name: String!
  type: FileType!
}

enum FileType {
  dir
  file
}

...
```

However, when I try running the builder, I get the follow error:

```
[SEVERE] built_value_generator:built_value on lib/graphql/__generated__/fragments.data.gql.dart:
Error in BuiltValueGenerator for abstract class GFileFragmentData implements Built<GFileFragmentData, dynamic>, GFileFragment.
Please make the following changes to use BuiltValue:

1. Make field type have non-dynamic type. If you are already specifying a type, please make sure the type is correctly imported.
```

<details>
<summary>build.yaml</summary>
```yaml
targets:
  $default:
    builders:
      gql_build|schema_builder:
        enabled: true
        options:
          type_overrides:
            DateTime:
              name: DateTime
      gql_build|ast_builder:
        enabled: true
        options:
          type_overrides:
            DateTime:
              name: DateTime
      gql_build|data_builder:
        enabled: true
        options:
          schema: restic_app|lib/graphql/schema.gql
          type_overrides:
            DateTime:
              name: DateTime
      gql_build|var_builder:
        enabled: true
        options:
          schema: restic_app|lib/graphql/schema.gql
          type_overrides:
            DateTime:
              name: DateTime
      gql_build|serializer_builder:
        enabled: true
        options:
          schema: restic_app|lib/graphql/schema.gql
          type_overrides:
            DateTime:
              name: DateTime
          custom_serializers:
            - import: 'package:restic_app/graphql/date_serializer.dart'
              name: DateSerializer

      ferry_generator|req_builder:
        enabled: true
        options:
          schema: restic_app|lib/graphql/schema.gql
          type_overrides:
            DateTime:
              name: DateTime
```
</details>

I've tested using the most up to date version, as well as the beta version.
