### ISSUE TITLE
On windows, build_runner fails

### ISSUE THREAD

**Issue by simpai** [gql-dart/ferry#298]
When I run 

`pub run build_runner build`

it fails with

`[SEVERE] built_value_generator:built_value on lib/data/graphql/__generated__/all_games.req.gql.dart:
Error in BuiltValueGenerator for abstract class GQueryReq implements Built<GQueryReq, dynamic>, OperationRequest<dynamic, dynamic>.
Please make the following changes to use BuiltValue:
`

The failure is caused by using '\' instead of '/' in the import statement, like this:

`import 'package:portal\data\graphql\__generated__\all_games.ast.gql.dart'`

and it works well on Mac without any problem.

**Comment by smkhalsa** [comment]
Why are you using `\` instead of `/` in your file path?

**Comment by smkhalsa** [comment]
I suggest posting your `.graphql` and `built.yaml` files on the discord and asking for help there.

**Comment by simpai** [comment]
It works well on Mac without any problem.
It is simply windows path delimiter problem.

**Comment by ambiguous48** [comment]
This issue was fixed a few months ago. Update your dart/flutter.

See here:
https://github.com/dart-lang/pub/issues/3012

**Comment by simpai** [comment]
@ambiguous48 it doesn't seem to be fixed. 

`> flutter --version
Flutter 2.5.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 18116933e7 (4 weeks ago) • 2021-10-15 10:46:35 -0700
Engine • revision d3ea636dc5
Tools • Dart 2.14.4`

some files are fine but some are not.

![image](https://user-images.githubusercontent.com/7153324/141886652-698557ab-c621-406f-8656-db204216dfaf.png)

**Comment by ambiguous48** [comment]
Could your issue be related to https://github.com/gql-dart/gql/issues/224 or https://github.com/gql-dart/gql/issues/239?

**Comment by simpai** [comment]
@ambiguous48 
@smkhalsa
It is also reproduced in the pokemon example as well. 

[pokemon_explorer.zip](https://github.com/gql-dart/ferry/files/7552047/pokemon_explorer.zip)

**Comment by yamasite** [comment]
I ran [this tutorial](https://codelabs.developers.google.com/codelabs/flutter-github-graphql-client/index.html#4) in Windows and met the same problem after `flutter pub run build_runner build --delete-conflicting-outputs`:

![image](https://user-images.githubusercontent.com/10089260/148491575-97a96bd4-8582-4bca-96aa-8526ecc084fb.png)
![image](https://user-images.githubusercontent.com/10089260/148491600-984add0f-a9c2-47c9-a6be-0998291b8a3e.png)

The generated code created weird delimiters and caused the command to fail.

**Comment by axrs** [comment]
I forked the project and made a small change (https://github.com/axrs/ferry/commit/b9dc4b109515271ce4e50ad65ae849dd0dd4d830) which makes all paths posix based.

This fixed the issue for me in generating files for the GitHub Schema in MacOS and Windows. It may fix it for you. You can test it by changing `ferry_generator` in your `pubspec.yaml`

```yaml
dev_dependencies:
  ferry_generator:
    git: #Try and not use a fork
      url: https://github.com/axrs/ferry.git
      path: packages/ferry_generator
```

**Comment by nyelnizy** [comment]
@axrs  pointing ferry_generator to the fork  gets stuck on pub get, I have been trying to get this to work for hours but nothing seems to work, flutter --version shows this : Flutter 2.10.3  Tools • Dart 2.16.1 • DevTools 2.9.2.

**Comment by axrs** [comment]
@nyelnizy 

I'm not sure what's going on. This is what we have:

```
name: <name>
description: <description>
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.14.4 <3.0.0"

dev_dependencies:
  build_runner: ^2.1.7
  ferry_generator:
    git: #Try and not use a fork
      url: https://github.com/axrs/ferry.git
      path: packages/ferry_generator
  glob: ^2.0.2
  lints: ^1.0.1
  logging: ^1.0.2
  path: ^1.8.0

dependencies:
  ferry: 0.10.5-dev.2 #TODO update to release version
  gql_http_link: ^0.4.0
  http: ^0.13.4

dependency_overrides:
  analyzer: ^2.8.0
```

I just did a fresh install and everything compiled and ran tests without an issue.

```
Flutter 2.10.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 097d3313d8 (4 weeks ago) • 2022-02-18 19:33:08 -0600
Engine • revision a83ed0e5e3
Tools • Dart 2.16.1 • DevTools 2.9.2
```

You could clone the project fork locally, and use the `dependency_overrides` to specify a path. That _might_ help.
