### ISSUE TITLE
[Error] JSON types cannot be correctly deserialized 

### ISSUE THREAD

**Issue by warcayac** [gql-dart/ferry#314]
I have this query:
```
query QuoteRequests($page: Int!) {
  getQuoteRequestsList(page: $page) {
    vehicle
    body
    licensePlate
    vin
    quality
    currency
    items
  }
}
```
It generates this sample result:

```
{
    "data": {
        "getQuoteRequestsList": [
            {
                "vehicle": "1997 TOYOTA AVALON 4 DR ",
                "body": "Sedan",
                "licensePlate": "RHJ456",
                "vin": "XBGGDFYYREAXVJJJD",
                "quality": [
                    "GENUINO"
                ],
                "currency": "USD",
                "items": [
                    {
                        "uid": "74355f85-5312-9999-8acd-709ceccda00a",
                        "name": "Doble cero que es",
                        "description": "no me interesa",
                        "quantity": 11
                    },
                    {
                        "uid": "66db6fe0-1044-4d58-8454-5e51ab7a313f",
                        "name": "El arenero",
                        "description": "el duende verde",
                        "quantity": 2
                    }
                ]
            },
        ]
    }
}
```
The **items** data is a JSON type, and when trying to fetch that data with
```
client.request(GQuoteRequestsReq((b) => b..vars.page = 0)).listen((response) => print(response.data.toString()));
```
I get a Null result, but if I leave **items** out of the query, I get a no-null result. I have no problem if I run that query using the **HTTP** package.

This is an error or I need to configure something?

Thanks.

## UPDATE
This is definitely an error because if I try to make a hot-reload in Flutter I get this error in debug console:
```
Reloaded 1 of 1700 libraries in 860ms.
E/flutter ( 2286): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Deserializing '[__typename, Query, getQuoteRequestsList, [{__typename: GetQuoteRequestsRecor...' to 'GQuoteRequestsData' failed due to: Deserializing '[{__typename: GetQuoteRequestsRecord, uid: 0bf6709f-7ab7-464e-8ee3-6a94e46f05...' to 'BuiltList<GQuoteRequestsData_getQuoteRequestsList>' failed due to: Deserializing '[__typename, GetQuoteRequestsRecord, uid, 0bf6709f-7ab7-464e-8ee3-6a94e46f057...' to 'GQuoteRequestsData_getQuoteRequestsList' failed due to: Deserializing '[{uid: 16870250-5acb-4c23-a7e4-f4e23bbd23ad, name: Doble cero que es, descrip...' to 'GJSON' failed due to: type 'List<dynamic>' is not a subtype of type 'String?' in type cast
E/flutter ( 2286): #0      BuiltJsonSerializers._deserialize
package:built_value/src/built_json_serializers.dart:178
E/flutter ( 2286): #1      BuiltJsonSerializers.deserialize
package:built_value/src/built_json_serializers.dart:124
```
It's clear it is fetching the expected result but it cannot deserialize properly, then it returns a null result.

**Comment by jimshepherd** [comment]
I am receiving a similar error deserializing a JSON type. In my case, the JSON field is a simple map, not an array of maps as in your case.

Here is a representative error:
`...failed due to: Deserializing '[100px, https://storage.googleapis.com/...' to 'GJson' failed due to: type 'List<Object?>' is not a subtype of type 'String?' in type cast)`

Note that the actual response for this example using other clients is {"100px": "https://storage.googleapis.com/..."}. It seems that either prior or during the deserialization, the curly braces are replaced with square brackets which are then interpreted as a list.

Any suggestions on where to begin debugging?

**Comment by jhlabs** [comment]
I have the same issue. In my case the value for the json object was simply an empty object `{}` that returns `Deserializing '[]' to 'GJson' failed due to: type 'List<Object?>' is not a subtype of type 'String?' in type cast)`.

**Comment by jimshepherd** [comment]
Found a solution to the errors I was receiving. Basically, a custom serializer IS required to handle JSON types.

Here is the build.yaml I am using based on posts to the ferry discord channel:
```
targets:
  $default:
    builders:
      gql_build|schema_builder:
        enabled: true
        options:
          type_overrides:
            Json:
              name: JsonObject
              import: "package:built_value/json_object.dart"
      gql_build|ast_builder:
        enabled: true
      gql_build|data_builder:
        enabled: true
        options:
          schema: illhavea|lib/schema.graphql
          type_overrides:
            Json:
              name: JsonObject
              import: "package:built_value/json_object.dart"
      gql_build|var_builder:
        enabled: true
        options:
          schema: illhavea|lib/schema.graphql
          type_overrides:
            Json:
              name: JsonObject
              import: "package:built_value/json_object.dart"
      gql_build|serializer_builder:
        enabled: true
        options:
          schema: illhavea|lib/schema.graphql
          custom_serializers:
            - import: "package:built_value/src/json_object_serializer.dart"
              name: JsonObjectSerializer

      ferry_generator|req_builder:
        enabled: true
        options:
          schema: illhavea|lib/schema.graphql
          type_overrides:
            Json:
              name: JsonObject
              import: "package:built_value/json_object.dart"

```
