### ISSUE TITLE
How can i use multiple schemas?

### ISSUE THREAD

**Issue by cloneconf** [gql-dart/ferry#315]
I want to use two schemas in my app, is there a way to do that?

```
- graphql
 - api1
   schema.graphql
   user.graphql
 - api2
   schema.graphql
   trends.graphql
```

They both have different endpoints and **schemas**, is there any way to enable this?
Thanks in advance!

**Comment by cloneconf** [comment]
I think that using new 'modules' for every schema could work if we initialize the clients there...
for example:

```
- my_app
  - api1_graphql
    - lib
      - graphql
        - schema.graphql
        - user.graphql
      - client.dart
  - api2_graphql
    - lib
      - graphql
        - schema.graphql
        - trends.graphql
      - client.dart
  - lib
    - main.dart
```

but it's kinda work..
I'm curious to know if this feature `multi-schema` does exist already :smile:

**Comment by smkhalsa** [comment]
Yes, it's possible with a custom link.

Closing this since we use GitHub for bug reports and feature requests. 

Please feel free to ask for assistance on the discord.

**Comment by cloneconf** [comment]
Hello @smkhalsa!

> Yes, it's possible with a **_custom link_**.

Actually this doesn't help :sweat_smile:

I have two completely **different** Graphql endpoints and **schemas**, and I want to use them both in my app.

Example:

My schemas:

```bash
lib
└── graphql
    ├── example
    │   ├── schema.graphql
    │   └── user.graphql
    └── hello
        ├── schema.graphql
        └── trends.graphql
```

```
```

**Comment by smkhalsa** [comment]
There are you that show you to merge schemas. Maybe you could try one of those?

**Comment by cloneconf** [comment]
I played -a lot- with the `build.yaml`, and i found that there is some kinda a ... bug?

By replacing `:` (seems the legacy one) to `|` I was able to run two identical packages in the same builder:


![Screenshot_2021-12-25_14-15-03](https://user-images.githubusercontent.com/88058138/147385725-082e1895-7480-4d77-a471-595d42495409.png)

It gives me `Schema validation: String violates the pattern: '^(?:\w*\|)?\w+$' `, however it does work!

**I was able to use two identical methods in the same builder by replace the `:`!**

I was able to build BUT what is this the right way?

It may break at any time.

What if there is a third schema :smile:

Here is the final file: (yeah its huge)

<details><summary>build.yaml</summary>

```yaml
targets:
  $default:
    builders:

      # First schema
      gql_build|schema_builder:
        generate_for:
          - lib/graphql/example/schema.example.graphql
        enabled: true
      gql_build|ast_builder:
        generate_for:
          - lib/graphql/example/schema.example.graphql
        enabled: true
      gql_build|data_builder:
        generate_for:
          - lib/graphql/example/schema.example.graphql
        enabled: true
        options:
          schema: my_app|lib/graphql/example/schema.example.graphql
      gql_build|var_builder:
        generate_for:
          - lib/graphql/example/schema.example.graphql
        enabled: true
        options:
          schema: my_app|lib/graphql/example/schema.example.graphql
      gql_build|serializer_builder:
        generate_for:
          - lib/graphql/example/schema.example.graphql
        enabled: true
        options:
          schema: lib/graphql/example/schema.example.graphql
      ferry_generator|req_builder:
        generate_for:
          - lib/graphql/example/schema.example.graphql
        enabled: true
        options:
          schema: my_app|lib/graphql/example/schema.example.graphql


      # Second schema
      gql_build:schema_builder:
        generate_for:
          - lib/graphql/two/schema.two.graphql
        enabled: true
      gql_build:ast_builder:
        generate_for:
          - lib/graphql/two/schema.two.graphql
        enabled: true
      gql_build:data_builder:
        generate_for:
          - lib/graphql/two/schema.two.graphql
        enabled: true
        options:
          schema: lib/graphql/two/schema.two.graphql
      gql_build:var_builder:
        generate_for:
          - lib/graphql/two/schema.two.graphql
        enabled: true
        options:
          schema: lib/graphql/two/schema.two.graphql
      gql_build:serializer_builder:
        generate_for:
          - lib/graphql/two/schema.two.graphql
        enabled: true
        options:
          schema: my_app|lib/graphql/two/schema.two.graphql
      ferry_generator:req_builder:
        generate_for:
          - lib/graphql/two/schema.graphql
        enabled: true
        options:
          schema: my_app|lib/graphql/two/schema.two.graphql
```

</details>


However, I believe that this is possible but I don't know how, so here I ask you?

Does multiple builders is the right own? (I really don't know)

You are already know how build works, what is the best method to this? :smile:

**Comment by cloneconf** [comment]
Hello @smkhalsa !

I seem to find the solution :)
I had to override some stuff but it works really well !

This is my `build.yaml` file:

```yaml
targets:

  # schema for api 1
  $default:
    builders:
      gql_build|schema_builder:
        generate_for:
          - lib/graphql/api1/**
        enabled: true
      gql_build|ast_builder:
        generate_for:
          - lib/graphql/api1/**
        enabled: true
      gql_build|data_builder:
        generate_for:
          - lib/graphql/api1/**
        enabled: true
        options:
          schema: multiple_graphql_ferry|lib/graphql/api1/schema.graphql
      gql_build|var_builder:
        generate_for:
          - lib/graphql/api1/**
        enabled: true
        options:
          schema: multiple_graphql_ferry|lib/graphql/api1/schema.graphql
      gql_build|serializer_builder:
        generate_for:
          - lib/graphql/api1/**
        enabled: true
        options:
          schema: multiple_graphql_ferry|lib/graphql/api1/schema.graphql
      ferry_generator|req_builder:
        generate_for:
          - lib/graphql/api1/**
        enabled: true
        options:
          schema: multiple_graphql_ferry|lib/graphql/api1/schema.graphql

      # override
      gql_build:schema_builder:
        generate_for:
          - lib/graphql/api1/**
      built_value_generator:built_value:
        generate_for:
          - lib/graphql/api1/**
      source_gen:combining_builder:
        generate_for:
          - lib/graphql/api1/**




  # schema for api 2
  schema_api_two:
    builders:
      gql_build|schema_builder:
        generate_for:
          - lib/graphql/api2/**
        enabled: true
      gql_build|ast_builder:
        generate_for:
          - lib/graphql/api2/**
        enabled: true
      gql_build|data_builder:
        generate_for:
          - lib/graphql/api2/**
        enabled: true
        options:
          schema: multiple_graphql_ferry|lib/graphql/api2/schema.graphql
      gql_build|var_builder:
        generate_for:
          - lib/graphql/api2/**
        enabled: true
        options:
          schema: multiple_graphql_ferry|lib/graphql/api2/schema.graphql
      gql_build|serializer_builder:
        generate_for:
          - lib/graphql/api2/**
        enabled: true
        options:
          schema: multiple_graphql_ferry|lib/graphql/api2/schema.graphql
      ferry_generator|req_builder:
        generate_for:
          - lib/graphql/api2/**
        enabled: true
        options:
          schema: multiple_graphql_ferry|lib/graphql/api2/schema.graphql
        
      
      # override
      gql_build:schema_builder:
        generate_for:
          - lib/graphql/api2/**
      built_value_generator:built_value:
        generate_for:
          - lib/graphql/api2/**
      source_gen:combining_builder:
        generate_for:
          - lib/graphql/api2/**
```

Thanks you again :heart:

**Comment by qbait** [comment]
I'm trying to achieve multiple schemas as well.
@cloneconf, unfortunately, your `build.yaml` is not generating serializers properly.
![unnamed](https://user-images.githubusercontent.com/2264901/148513907-461440f7-0f2b-487d-8282-e823257dcbe8.png)

Any thoughts on that?
My sample code is available at https://github.com/qbait/multiple_schemas

**Comment by cloneconf** [comment]
You are right @qbait 

commenting the `generate for` for the  `gql_build|serializer_builder` worked for me!
please let me now if its work for you ;)

```yaml
targets:

  # schema for api 1
  $default:
    builders:
      gql_build|schema_builder:
        generate_for:
          - lib/graphql/api1/**
        enabled: true
      gql_build|ast_builder:
        generate_for:
          - lib/graphql/api1/**
        enabled: true
      gql_build|data_builder:
        generate_for:
          - lib/graphql/api1/**
        enabled: true
        options:
          schema: multiple_schemas|lib/graphql/api1/schema.graphql
      gql_build|var_builder:
        generate_for:
          - lib/graphql/api1/**
        enabled: true
        options:
          schema: multiple_schemas|lib/graphql/api1/schema.graphql
      gql_build|serializer_builder:
        # generate_for:
        #   - lib/graphql/api1/**
        enabled: true
        options:
          schema: multiple_schemas|lib/graphql/api1/schema.graphql
      ferry_generator|req_builder:
        generate_for:
          - lib/graphql/api1/**
        enabled: true
        options:
          schema: multiple_schemas|lib/graphql/api1/schema.graphql

      # override
      gql_build:schema_builder:
        generate_for:
          - lib/graphql/api1/**
      built_value_generator:built_value:
        generate_for:
          - lib/graphql/api1/**
      source_gen:combining_builder:
        generate_for:
          - lib/graphql/api1/**


  # schema for api 2
  schema_api_two:
    builders:
      gql_build|schema_builder:
        generate_for:
          - lib/graphql/api2/**
        enabled: true
      gql_build|ast_builder:
        generate_for:
          - lib/graphql/api2/**
        enabled: true
      gql_build|data_builder:
        generate_for:
          - lib/graphql/api2/**
        enabled: true
        options:
          schema: multiple_schemas|lib/graphql/api2/schema.graphql
      gql_build|var_builder:
        generate_for:
          - lib/graphql/api2/**
        enabled: true
        options:
          schema: multiple_schemas|lib/graphql/api2/schema.graphql
      gql_build|serializer_builder:
        # generate_for:
        #   - lib/graphql/api2/**
        enabled: true
        options:
          schema: multiple_schemas|lib/graphql/api2/schema.graphql
      ferry_generator|req_builder:
        generate_for:
          - lib/graphql/api2/**
        enabled: true
        options:
          schema: multiple_schemas|lib/graphql/api2/schema.graphql


      # override
      gql_build:schema_builder:
        generate_for:
          - lib/graphql/api2/**
      built_value_generator:built_value:
        generate_for:
          - lib/graphql/api2/**
      source_gen:combining_builder:
        generate_for:
          - lib/graphql/api2/**
```
