### ISSUE TITLE
FetchPolicy.serializer being included but not generated

### ISSUE THREAD

**Issue by williamhjcho** [gql-dart/ferry#328]
Hi! 👋 

I was trying out the latest dev version(s) to get the `__generated__` directories and I'm having problems when running tests (the app itself runs fine), due to this [FetchPolicy.serializer](https://github.com/gql-dart/ferry/blob/master/examples/pokemon_explorer/lib/__generated__/serializers.gql.g.dart#L10) in `serializer.gql.g.dart` being generated, but not actually existing.

```yaml
dependencies:
  (...)
  ferry: ^0.10.5-dev.2
  gql_http_link: ^0.4.0

dev_dependencies:
  (...)
  build_runner: ^2.1.2
  ferry_generator: ^0.5.0-dev.9
```
