### ISSUE TITLE
Cannot use ferry inside a flutter package

### ISSUE THREAD

**Issue by sbatezat** [gql-dart/ferry#342]
I've got my main flutter application (./lib) with 2 internal packages, let's say A, B (./lib/packages/A/lib, ./lib/packages/B/lib).
All ferry stuff (and dependencies) are inside the package A :

```yaml
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  build_runner: ^2.1.8
  injectable_generator: ^1.4.1
  ferry_generator: ^0.4.4
```

A function on my flutter application called package B which call package A with a ferry request.
An error is thrown "Error: Couldn't resolve the package 'gql_code_builder'".
Adding manually the gql_code_builder to the A package doesn't solve the issue, but adding it to the application is a working workaround.

See https://stackoverflow.com/questions/71080540/error-couldnt-resolve-the-package-gql-code-builder-from-repository-layer/
