### ISSUE TITLE
The cache causes memory leak

### ISSUE THREAD

**Issue by T-moz** [gql-dart/ferry#343]
**Setting a FetchPolicy that read data in cache cause memory leak**

Each time, a widget start to read the cache, memory usage increase and never go down.

Here are the result of the leak by `FetchPolicy` and type of `Store`:

  | CacheOnly | CacheFirst | CacheAndNetwork | NetworkOnly | NoCache
-- | -- | -- | -- | -- | --
HiveStore | Leak | Leak | Leak | No Leak | No Leak
Memory Store | Leak | Leak | Leak | No Leak | No Leak

By elimination, the top method that causes the leak should be `CacheTypedLink.request`.

# Minimal step to reproduce the bug:

https://github.com/T-moz/ferry_memory_leak

![Kapture 2022-03-26 at 18 12 56](https://user-images.githubusercontent.com/28344195/160250263-8b5f865f-f92d-40f4-b202-bda2e2fb910d.gif)

Pubspec:
```yaml
name: ferry_memory_leak
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  ferry: ^0.10.5-dev.3
  gql_http_link: ^0.4.0
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  ferry_hive_store: ^0.4.4
  ferry_flutter: ^0.5.5-dev.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  ferry_generator: ^0.5.0-dev.10
  build_runner: ^2.1.7
  gql_exec: ^0.4.0
  gql_build: ^0.4.0
  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

```

This way to reproduce the bug can look kind of dumb. But the real life problem is, the more a user use the app, the more the memory usage will go up.

Thanks for your work. I'm available to help fix this if needed
