### ISSUE TITLE
Stuck on build runner generation

### ISSUE THREAD

**Issue by lodisy** [gql-dart/ferry#345]
It always stuck when generating the `serializers.gql.dart` file (over 10 minutes):

```
...
[FINE] built_value_generator:built_value on lib/widgets/widgets.dart:Running BuiltValueGenerator
[FINE] built_value_generator:built_value on lib/widgets/form_input_date.dart:Running BuiltValueGenerator
[FINE] built_value_generator:built_value on lib/widgets/form_input_id.dart:Running BuiltValueGenerator
[FINE] built_value_generator:built_value on lib/widgets/responsive.dart:Running BuiltValueGenerator
[FINE] built_value_generator:built_value on lib/core/user/data/remote/__generated__/user.ast.gql.dart:Running BuiltValueGenerator
[FINE] built_value_generator:built_value on lib/widgets/model_fit.dart:Running BuiltValueGenerator
[FINE] built_value_generator:built_value on lib/__generated__/schema.ast.gql.dart:Running BuiltValueGenerator
[INFO] Heartbeat:1m 1s elapsed, 84/94 actions completed.
[FINE] built_value_generator:built_value on lib/core/user/data/remote/__generated__/user.data.gql.dart:Running BuiltValueGenerator
[FINE] built_value_generator:built_value on lib/__generated__/schema.schema.gql.dart:Running BuiltValueGenerator
[FINE] built_value_generator:built_value on lib/core/user/data/remote/__generated__/user.req.gql.dart:Running BuiltValueGenerator
[FINE] built_value_generator:built_value on lib/core/user/data/remote/__generated__/user.var.gql.dart:Running BuiltValueGenerator
[FINE] built_value_generator:built_value on lib/__generated__/serializers.gql.dart:Running BuiltValueGenerator
^C%                                                                                                   
```

build.yaml:

```
targets:
    $default:
        builders:
            ferry_generator|serializer_builder:
                enabled: true
                options:
                    schema: admin_flutter|lib/schema.graphql

            ferry_generator|graphql_builder:
                enabled: true
                options:
                    schema: admin_flutter|lib/schema.graphql
```
