### ISSUE TITLE
Generating for types with multiple interfaces is either stuck/failing

### ISSUE THREAD

**Issue by nabilshuja** [gql-dart/ferry#347]
Generating graphql that contains a `type` which would implement multiple interfaces tend to get stuck.

As an example, generating for graphql is failing on the type `Swallow`

```graphql
schema {
    query: Query
}

type Query {
    someSwallow: Swallow!
}

interface Bird {
    wingspan: Int!
}

interface Animal {
    speed: Int!
}

type Swallow implements Animal & Bird {
    wingspan: Int!
    speed: Int!
}
```

My Pubspec Dependencies:

```yaml
dependencies:
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  gql_link: ^0.4.2
  gql_http_link: ^0.4.2
  gql_transform_link: ^0.2.2
  gql_error_link: ^0.2.2
  ferry: ^0.10.5-dev.3
  ferry_hive_store: ^0.4.5-dev.1
  gql_code_builder: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  build_runner: ^2.1.8
  flutter_gen_runner: ^4.1.6
  json_serializable: ^6.1.5
  ferry_generator: ^0.5.0-dev.10
  envify_generator: ^2.0.2
  gql_build: ^0.4.0
```
