### ISSUE TITLE
Build failing: misconfigured builder definition

### ISSUE THREAD

**Issue by MubeenNaeem** [gql-dart/ferry#349]
I am running
`flutter pub run build_runner build --delete-conflicting-outputs`

[INFO] Generating build script...
[INFO] Generating build script completed, took 400ms

[INFO] Precompiling build script......
[WARNING] /C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/gql_code_builder-0.2.0/lib/src/ast.dart:618:12: Erro
r: A non-null value must be returned since the return type 'Expression' doesn't allow null.
 - 'Expression' is from 'package:code_builder/src/specs/expression.dart' ('/C:/src/flutter/.pub-cache/hosted/pub.
dartlang.org/code_builder-4.1.0/lib/src/specs/expression.dart').
Expression _directiveLocation(DirectiveLocation location) {
           ^
[INFO] Precompiling build script... completed, took 6.2s

[SEVERE] Failed to precompile build script .dart_tool/build/entrypoint/build.dart.
This is likely caused by a misconfigured builder definition.

pub finished with exit code 78

**Comment by appinteractive** [comment]
I have exactly the same issue here! @MubeenNaeem @smkhalsa

**Comment by jigneshpatel-dreampay** [comment]
I am facing same issue. It is because of one switch case is missing in ast.dart (Expression _directiveLocation(DirectiveLocation location) method).

```
case DirectiveLocation.variableDefinition:
      return _ref("DirectiveLocation.variableDefinition");

```

Which is already solved in version gql_code_builder: 0.5.1

So you guys need to point to 0.5.1 instead of 0.2.0 for gql_code_builder.

**Comment by appinteractive** [comment]
For me, the fix was using all stable versions of ferry and associated packages and pinning following versions:

```yaml
ependency_overrides:
  analyzer: ^3.3.0
  gql: 0.13.0
  ```

**Comment by nottmey** [comment]
@appinteractive Your workaround did not work for me. This error occured:
```
Failed to build build_runner:build_runner:
../../.pub-cache/hosted/pub.dartlang.org/build_resolvers-2.0.4/lib/src/resolver.dart:173:29: Error: The method 'getResolvedLibrary2' isn't defined for the class 'AnalysisSessionImpl'.
 - 'AnalysisSessionImpl' is from 'package:analyzer/src/dart/analysis/session.dart' ('../../.pub-cache/hosted/pub.dartlang.org/analyzer-3.4.1/lib/src/dart/analysis/session.dart').
Try correcting the name to the name of an existing method, or defining a method named 'getResolvedLibrary2'.
      return (await session.getResolvedLibrary2(path) as ResolvedLibraryResult)
                            ^^^^^^^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dartlang.org/build_resolvers-2.0.4/lib/src/resolver.dart:177:23: Error: The method 'getParsedLibrary2' isn't defined for the class 'AnalysisSessionImpl'.
 - 'AnalysisSessionImpl' is from 'package:analyzer/src/dart/analysis/session.dart' ('../../.pub-cache/hosted/pub.dartlang.org/analyzer-3.4.1/lib/src/dart/analysis/session.dart').
Try correcting the name to the name of an existing method, or defining a method named 'getParsedLibrary2'.
      return (session.getParsedLibrary2(path) as ParsedLibraryResult)
                      ^^^^^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dartlang.org/build_resolvers-2.0.4/lib/src/build_asset_uri_resolver.dart:126:26: Error: The method 'updateFile' isn't defined for the class 'MemoryResourceProvider'.
 - 'MemoryResourceProvider' is from 'package:analyzer/file_system/memory_file_system.dart' ('../../.pub-cache/hosted/pub.dartlang.org/analyzer-3.4.1/lib/file_system/memory_file_system.dart').
Try correcting the name to the name of an existing method, or defining a method named 'updateFile'.
        resourceProvider.updateFile(path, content);
                         ^^^^^^^^^^
../../.pub-cache/hosted/pub.dartlang.org/build_resolvers-2.0.4/lib/src/analysis_driver.dart:38:13: Error: Couldn't find constructor 'SummaryBasedDartSdk'.
  var sdk = SummaryBasedDartSdk(sdkSummaryPath, true);
            ^^^^^^^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dartlang.org/build_resolvers-2.0.4/lib/src/analysis_driver.dart:44:35: Error: Too many positional arguments: 0 allowed, but 1 found.
Try removing the extra positional arguments.
  var dataStore = SummaryDataStore([sdkSummaryPath]);
                                  ^
../../.pub-cache/hosted/pub.dartlang.org/analyzer-3.4.1/lib/src/summary/package_bundle_reader.dart:112:7: Context: The class 'SummaryDataStore' has a constructor that takes no arguments.
class SummaryDataStore {
      ^
../../.pub-cache/hosted/pub.dartlang.org/build_resolvers-2.0.4/lib/src/analysis_driver.dart:51:30: Error: Too many positional arguments: 0 allowed, but 8 found.
Try removing the extra positional arguments.
  var driver = AnalysisDriver(
                             ^
../../.pub-cache/hosted/pub.dartlang.org/analyzer-3.4.1/lib/src/dart/analysis/driver.dart:255:3: Context: Found this candidate, but the arguments don't match.
  AnalysisDriver({
  ^^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dartlang.org/dart_style-2.1.1/lib/src/source_visitor.dart:2695:22: Error: Type 'TypeName' not found.
  void visitTypeName(TypeName node) {
                     ^^^^^^^^
../../.pub-cache/hosted/pub.dartlang.org/dart_style-2.1.1/lib/src/source_visitor.dart:2695:22: Error: 'TypeName' isn't a type.
  void visitTypeName(TypeName node) {
                     ^^^^^^^^
pub finished with exit code 1
```

**Comment by appinteractive** [comment]
@nottmey I indeed had to change my build to use gql_build directly: 

```yml
targets:
  $default:
    builders:
      gql_build|schema_builder:
        enabled: true
        options:
          type_overrides:
            Date:
              name: DateTime
      gql_build|ast_builder:
        enabled: true
        options:
          type_overrides:
            Date:
              name: DateTime
      gql_build|data_builder:
        enabled: true
        options:
          schema: my_app|lib/graphql/schema.graphql
          type_overrides:
            Date:
              name: DateTime
      gql_build|var_builder:
        enabled: true
        options:
          schema: my_app|lib/graphql/schema.graphql
          type_overrides:
            Date:
              name: DateTime
      gql_build|serializer_builder:
        enabled: true
        options:
          schema: my_app|lib/graphql/schema.graphql
          custom_serializers:
            - import: "package:my_app/date_serializer.dart"
              name: DateSerializer
      ferry_generator|req_builder:
        enabled: true
        options:
          schema: my_app|lib/graphql/schema.graphql
          type_overrides:
            Date:
              name: DateTime
```

**Comment by AristideVB** [comment]
@appinteractive Could you share your complete pubspec.yaml ? I'm having issues finding the right dependencies & version for the generator to work

**Comment by appinteractive** [comment]
@AristideVB sure, here my shortened pubspec.yaml

```yaml
module:
  androidX: true

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  ferry_flutter: ^0.5.4
  ferry_hive_store: ^0.4.4
  ferry: ^0.10.4
  flutter:
    sdk: flutter
  gql_dedupe_link: ^2.0.0
  gql_error_link: ^0.2.0
  gql_http_link: ^0.4.0
  gql_link: ^0.4.0
  gql_transform_link: ^0.2.0

dev_dependencies:
  build_runner: ^2.1.8
  ferry_generator: ^0.4.4
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  test: any
  gql_build:

dependency_overrides:
  analyzer: ^3.3.0
  gql: 0.13.0
```  

and here my build.yaml
```yaml
targets:
  $default:
    builders:
      gql_build|schema_builder:
        enabled: true
        options:
          type_overrides:
            Date:
              name: DateTime
      gql_build|ast_builder:
        enabled: true
        options:
          type_overrides:
            Date:
              name: DateTime
      gql_build|data_builder:
        enabled: true
        options:
          schema: your_app|lib/graphql/schema.graphql
          type_overrides:
            Date:
              name: DateTime
      gql_build|var_builder:
        enabled: true
        options:
          schema: your_app|lib/graphql/schema.graphql
          type_overrides:
            Date:
              name: DateTime
      gql_build|serializer_builder:
        enabled: true
        options:
          schema: your_app|lib/graphql/schema.graphql
          custom_serializers:
            - import: "package:your_app/date_serializer.dart"
              name: DateSerializer
      ferry_generator|req_builder:
        enabled: true
        options:
          schema: your_app|lib/graphql/schema.graphql
          type_overrides:
            Date:
              name: DateTime
```

and (bacause its in the build.yaml and I neede to change it too) my date_serializer.dart
```dart
import 'package:built_value/serializer.dart';

class DateSerializer implements PrimitiveSerializer<DateTime> {
  @override
  DateTime deserialize(
    Serializers serializers,
    Object serialized, {
    FullType specifiedType = FullType.unspecified,
  }) {
    assert(serialized is String,
        "DateSerializer expected 'String' but got ${serialized.runtimeType}");
    return DateTime.parse(serialized as String);
  }

  @override
  Object serialize(
    Serializers serializers,
    DateTime date, {
    FullType specifiedType = FullType.unspecified,
  }) {
    return date.toIso8601String();
  }

  @override
  Iterable<Type> get types => [DateTime];

  @override
  String get wireName => 'Date';
}
```

Hope that helps a bit 🤞
