### ISSUE TITLE
⛔️ Ferry is broken - unable to update schema.graphql

### ISSUE THREAD

**Issue by appinteractive** [gql-dart/ferry#350]
I'm unable (since weeks now) to update our schema.graphql and regenerate the classes with `flutter pub run build_runner build --delete-conflicting-outputs`. That started with an update of flutter (2.10.x), and I'm not able to fix it, no matter what. 

I did try the solutions of #348 #320 #349 with no effect, only the error messages change.

It seems that with newer version another build configuration is needed, but I do not get any information on this.
Now I'm stuck with my project and am not able to update it as the build fails with the new schema.

Messages I get (depending on the suggested voodoo fix) range from:

**latest stable versions** 
```sh
[WARNING] /opt/homebrew/Caskroom/flutter/2.10.3/flutter/.pub-cache/hosted/pub.dartlang.org/gql_code_builder-0.2.0/lib/src/ast.dart:618:12: Error: A non-null value must be returned since the return type 'Expression' doesn't allow null.
 - 'Expression' is from 'package:code_builder/src/specs/expression.dart' ('/opt/homebrew/Caskroom/flutter/2.10.3/flutter/.pub-cache/hosted/pub.dartlang.org/code_builder-4.1.0/lib/src/specs/expression.dart').
Expression _directiveLocation(DirectiveLocation location) {
```
**ferry_generator fork and newest dev versions** 
```sh
[WARNING] Configuring `ferry_generator:req_builder` in target `app:app` but this is not a known Builder
```

I'm really frustrated right now and standing in front of the decision to re-implement my whole IO logic to another package just to be able to update our product. 

Sorry if I'm sounding stressed here, but a product depends on that right now, and I'm clouless atm. I'm grateful for ANY help here.

**build.yaml**
```yaml
targets:
  $default:
    builders:
      gql_build|schema_builder:
        enabled: true
        options:
          type_overrides:
            Date:
              name: DateTime

      gql_build|ast_builder:
        enabled: true
        options:
          type_overrides:
            Date:
              name: DateTime

      gql_build|data_builder:
        enabled: true
        options:
          schema: app|lib/graphql/schema.graphql
          type_overrides:
            Date:
              name: DateTime

      gql_build|var_builder:
        enabled: true
        options:
          schema: app|lib/graphql/schema.graphql
          type_overrides:
            Date:
              name: DateTime

      gql_build|serializer_builder:
        enabled: true
        options:
          schema: app|lib/graphql/schema.graphql
          custom_serializers:
            - import: "package:app/date_serializer.dart"
              name: DateSerializer

      ferry_generator|req_builder:
        enabled: true
        options:
          schema: app|lib/graphql/schema.graphql
          type_overrides:
            Date:
              name: DateTime

```

**Comment by bgparkerdev** [comment]
I'm on flutter v2.10.4 and haven't noticed these issues. Have you tried to a different build.yaml file?

```
targets:
  $default:
    builders:
      ferry_generator|graphql_builder:
        enabled: true
        options:
          schema: something|lib/graphql/schema.graphql
          type_overrides:
            DKID:
              name: String
            ISODate:
              name: DateTime  
            Upload:
              name: MultipartFile
              import: 'package:http/http.dart'
      ferry_generator|serializer_builder:
        enabled: true
        options:
          schema: something|lib/graphql/schema.graphql
          custom_serializers:
            - import: 'something/graphql/date_serializer.dart'
              name: DateSerializer
            - import: 'something/graphql/upload_serializer.dart'
              name: UploadSerializer
          type_overrides:
            DKID:
              name: String
            ISODate:
              name: DateTime 
            Upload:
              name: MultipartFile
              import: 'package:http/http.dart'   

```

**Comment by bgparkerdev** [comment]
I'm on flutter 2.10.4 and haven't noticed these issues. Have you tried a different build.yaml file setup?

```
targets:
  $default:
    builders:
      ferry_generator|graphql_builder:
        enabled: true
        options:
          schema: something|lib/graphql/schema.graphql
          type_overrides:
            DKID:
              name: String
            ISODate:
              name: DateTime  
            Upload:
              name: MultipartFile
              import: 'package:http/http.dart'
      ferry_generator|serializer_builder:
        enabled: true
        options:
          schema: package|lib/graphql/schema.graphql
          custom_serializers:
            - import: 'package:something/graphql/date_serializer.dart'
              name: DateSerializer
            - import: 'package:something/graphql/upload_serializer.dart'
              name: UploadSerializer
          type_overrides:
            DKID:
              name: String
            ISODate:
              name: DateTime 
            Upload:
              name: MultipartFile
              import: 'package:http/http.dart'   

```

**Comment by appinteractive** [comment]
Thanks @bgparkerdev for that hint, but my issue still persists where I do not get build any request or vars for theme as the ferry_generator|req_builder does not get recognized at all.

**Comment by appinteractive** [comment]
When overwriting gql to version 0.13.0 like suggested here: https://stackoverflow.com/questions/71962457/severe-failed-to-precompile-build-script-dart-tool-build-entrypoint-build-d I do get at least no error. But the requests still don't get generated.

```yaml
dependency_overrides:
  analyzer: ^3.3.0
  gql: 0.13.0
```

**output** 
```sh
flutter pub run build_runner build --delete-conflicting-outputs
[INFO] Generating build script...
[INFO] Generating build script completed, took 635ms

[WARNING] Configuring `ferry_generator:var_builder` in target `news_or_fake:news_or_fake` but this is not a known Builder
[INFO] Initializing inputs
[INFO] Reading cached asset graph...
[WARNING] Throwing away cached asset graph because the build phases have changed. This most commonly would happen as a result of adding a new dependency or updating your dependencies.
[INFO] Cleaning up outputs from previous builds....
[INFO] Cleaning up outputs from previous builds. completed, took 14ms

[INFO] Generating build script...
[INFO] Generating build script completed, took 256ms

[WARNING] Invalidated precompiled build script due to missing asset graph.
[INFO] Precompiling build script......
[INFO] Precompiling build script... completed, took 1.1s

[WARNING] Configuring `ferry_generator:var_builder` in target `news_or_fake:news_or_fake` but this is not a known Builder
[INFO] Initializing inputs
[INFO] Building new asset graph...
[INFO] Building new asset graph completed, took 572ms

[INFO] Checking for unexpected pre-existing outputs....
[INFO] Checking for unexpected pre-existing outputs. completed, took 1ms

[INFO] Running build...
```

**Comment by appinteractive** [comment]
After restoring all files and running without the `--delete-conflicting-outputs` flag it might have worked... which is still very strange

**Comment by appinteractive** [comment]
So I can finaly confirm that the isue is gone with using all stable versions and pinning the versions:

```yaml
ependency_overrides:
  analyzer: ^3.3.0
  gql: 0.13.0
  ```

At least as long I do NOT use `--delete-conflicting-outputs`
