### ISSUE TITLE
How to create a custom serialiser for a scalar that doesn't override a default serializer

### ISSUE THREAD

**Issue by ValentinVignal** [gql-dart/ferry#354]
I have this schema :

```graphql
scalar MyScalar

type MyType {
  myNumber: Int!
  myScalar: MyScalar!
}
```

`MyScalar` is basically a `String` that contains an `int` so I created this custom serializer: 

```dart
class MyScalarSerializer implements PrimitiveSerializer<int> {
  @override
  int deserialize(
    Serializers serializers,
    Object serialized, {
    FullType specifiedType = FullType.unspecified,
  }) {
    assert(serialized is String,
        "MyScalarSerializer expected 'String' but got ${serialized.runtimeType}");
    return int.parse(serialized as String);
  }
  @override
  Object serialize(
    Serializers serializers,
    int myScalar, {
    FullType specifiedType = FullType.unspecified,
  }) =>
      myScalar.toString();
  @override
  Iterable<Type> get types => [int];

  @override
  String get wireName => 'int';
}
```

Here is my `build.yaml`: 

```yaml
  $default:
    sources:
      include:
        - lib/**
    builders:
      gql_build|schema_builder:
        enabled: true
        options:
          schema: my_project|lib/schema.graphql
          type_overrides:
            MyScalar:
              name: int
      gql_build|ast_builder:
        enabled: true
      gql_build|data_builder:
        enabled: true
        options:
          schema: my_project|lib/schema.graphql
          type_overrides:
            MyScalar:
              name: int
      gql_build|var_builder:
        enabled: true
        options:
          schema: my_project|lib/schema.graphql
          type_overrides:
            MyScalar:
              name: int
      gql_build|serializer_builder:
        enabled: true
        options:
          schema: my_project|lib/schema.graphql
          custom_serializers:
            - name: MyScalarSerializer
              import: "package:my_project/my_scalar_serializer.dart"
      ferry_generator|req_builder:
        enabled: true
        options:
          schema: my_project|lib/schema.graphql
          type_overrides:
            MyScalar:
              name: int
```

But then, `MyScalarSerializer` is also used de serialise and deserialise `myNumber`. It expects a `String` in the GraphQL response and tries to convert it in an int. But it is already an int.

How do I restrict `MyScalarSerializer` to be used only on `MyScalar` ?

**Comment by ramirezblindside** [comment]
@ValentinVignal did you have any luck on your issue?
I am trying something similar and also facing a similar issue.

**Comment by knaeckeKami** [comment]
I'm don't think this is possible in the current architecture.

But I can offer some workarounds:

-    By using
```yaml 
type_overrides:
            MyScalar:
              name: String
```
you get the original response as a String

- wrap the scalar in a custom wrapper object like here: https://ferrygraphql.com/docs/custom-scalars/  . you would have to access the `int` via something like `myType.myScalarWrapper.intValue` if your custom type wrapper looks like this
```dart
class MyScalarWrapper {
   final int intValue;
   MyScalarWrapper(this.intValue);
}
```
With that, you can add a `PrimitiveSerializer<MyScalarWrapper>`. 

Or you could ask in the built_value package (which implements the serialization) if they maybe know some other way to make this work.
