### ISSUE TITLE
Generate GraphQL relay classes is not working well

### ISSUE THREAD

**Issue by sahmadreza** [gql-dart/ferry#402]
Generating GraphQL classes is not working well.

in this example, `PhotoNode` and query `allPhoto` is not generated to dart.

**Flutter (Channel stable, 3.3.0, on Ubuntu 20.04.4 LTS 5.15.0-46-generic, locale
   en_US.UTF-8)**

pubspec.yaml
```
environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  ferry: ^0.11.0+1
  gql_http_link: ^0.4.4+1
  ferry_hive_store: ^0.4.5
  ferry_flutter: ^0.6.1+1
  get_it: ^7.2.0


dev_dependencies:
  analyzer: ^4.7.0
  build_runner: ^2.2.0
  flutter_launcher_icons: ^0.10.0
  hive_generator: ^1.1.3
  ferry_generator: ^0.6.0
```

**schema.graphql** :
```graphql
"""
The `ID` scalar type represents a unique identifier, often used to refetch an object or as key for a cache. The ID type appears in a JSON response as a String; however, it is not intended to be human-readable. When expected as an input type, any string (such as `"4"`) or integer (such as `4`) input value will be accepted as an ID.
"""
scalar GlobalID @specifiedBy(url: "https://relay.dev/graphql/objectidentification.htm")

"""An object with a Globally Unique ID"""
interface Node {
  """The Globally Unique ID of this object"""
  id: GlobalID!
}

"""Information to aid in pagination."""
type PageInfo {
  """When paginating forwards, are there more items?"""
  hasNextPage: Boolean!

  """When paginating backwards, are there more items?"""
  hasPreviousPage: Boolean!

  """When paginating backwards, the cursor to continue."""
  startCursor: String

  """When paginating forwards, the cursor to continue."""
  endCursor: String
}

type PhotoNode implements Node {
  id: GlobalID!
  title: String!

  """A "slug" is a unique URL-friendly title for an object."""
  slug: String!
  caption: String!
}

"""A connection to a list of items."""
type PhotoNodeConnection {
  """Pagination data for this connection"""
  pageInfo: PageInfo!

  """Contains the nodes in this connection"""
  edges: [PhotoNodeEdge!]!

  """Total quantity of existing nodes"""
  totalCount: Int
}

"""An edge in a connection."""
type PhotoNodeEdge {
  """A cursor for use in pagination"""
  cursor: String!

  """The item at the end of the edge"""
  node: PhotoNode!
}

"""All available queries for this schema."""
type Query {
  """Return Photo connection with pagination information."""
  allPhoto(
    """Returns the items in the list that come before the specified cursor."""
    before: String = null

    """Returns the items in the list that come after the specified cursor."""
    after: String = null

    """Returns the first n items from the list."""
    first: Int = null

    """Returns the items in the list that come after the specified cursor."""
    last: Int = null
  ): PhotoNodeConnection!
}

```

`schema.graphql` is generated by [strawberry GraphQL](https://strawberry.rocks/)
