### ISSUE TITLE
Getting XMLHttpRequest error for Web platform

### ISSUE THREAD

**Issue by warcayac** [gql-dart/ferry#435]
I have a GraphQL operation by using Ferry which works fine on Android platform, but if I try to run that operation for Web platform I get an error message found in `linkException` property from an `OperationResponse<TData, TVars>` object:

```
XMLHttpRequest error., originalStackTrace: 
dart-sdk/lib/_internal/js_dev_runtime/patch/core_patch.dart 963:28                get current
packages/http/src/browser_client.dart 69:22                                       <fn>
dart-sdk/lib/async/zone.dart 1653:54                                              runUnary
dart-sdk/lib/async/future_impl.dart 147:18                                        handleValue
dart-sdk/lib/async/future_impl.dart 766:44                                        handleValueCallback
dart-sdk/lib/async/future_impl.dart 795:13                                        _propagateToListeners
dart-sdk/lib/async/future_impl.dart 557:7                                         [_complete]
dart-sdk/lib/async/stream_pipe.dart 61:11                                         _cancelAndValue
dart-sdk/lib/async/stream.dart 1587:7                                             <fn>
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 334:14  _checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 339:39  dcall
dart-sdk/lib/html/dart2js/html_dart2js.dart 37341:58                              <fn>
, parsedResponse: null
```

I'm using these packages:
```
dependencies:
  ...
  built_value: ^8.4.1
  ferry: ^0.11.2+1
  ferry_flutter: ^0.6.2
  gql_http_link: ^0.4.4+1
  ...

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.2
  flutter_gen_runner: ^5.0.2
  ferry_generator: ^0.6.1
```

Environment info:
- Flutter 3.3.5 
- Dart 2.18.2
- EndeavourOS Linux x86_64, Kernel: 6.0.2-zen1-1-zen
- Flutter path: `~/Applications/flutter`
- VSCode version: 1.72.2
