### ISSUE TITLE
custom scalar ignored 0.6.1

### ISSUE THREAD

**Issue by MichalNemec** [gql-dart/ferry#446]
Hello,
im using `ferry_generator: 0.6.1` and i would need scalar for uuid

```yaml
targets:
  $default:
    builders:
      ferry_generator|graphql_builder:
        enabled: true
        options:
          schema: mobileapp|lib/api/graphql/schema.graphql
          types_override:
            uuid:
              name: String
      ferry_generator|serializer_builder:
        enabled: true
        options:
          schema: mobileapp|lib/api/graphql/schema.graphql
          custom_serializers:
            - import: "package:mobileapp/api/serializers/uuid_serializer.dart"
              name: uuidSerializer

```

```dart
import 'package:built_value/serializer.dart';

class uuidSerializer implements PrimitiveSerializer<String> {
  @override
  String deserialize(
    Serializers serializers,
    Object serialized, {
    FullType specifiedType = FullType.unspecified,
  }) {
    assert(
      serialized is String,
      "DateSerializer expected 'String' but got ${serialized.runtimeType}",
    );
    return serialized.toString();
  }

  @override
  Object serialize(
    Serializers serializers,
    String uuid, {
    FullType specifiedType = FullType.unspecified,
  }) =>
      uuid.toString();

  @override
  Iterable<Type> get types => [String];

  @override
  String get wireName => 'String';
}
```

its still showing up as Guuid, any tutorial for this?

i would completely need uuid -> string and jsonb to map
