### ISSUE TITLE
OfflineMutationTypedLink - Bad state: No serializer for '_Map<String, dynamic>'.

### ISSUE THREAD

**Issue by francescreig** [gql-dart/ferry#493]
Hello,

I have been integrating the OfflineMutationTypedLink with a mutationQueue that @akinsho started time ago on PR #147 but I have encountered into a serialization problem that arises when the request is sent to be serialized before added to que mutationQueue box (on Hive). The error that prompts is:
`Bad state: No serializer for '_Map<String, dynamic>'` and it happens when executing `mutationQueueBox.add(serializers.serialize(request));` line
and I think that it should be because some Serializers issue and not regarding any implementation on the offline link itself.

Do I need to create a custom serializer for this? Does not JsonSerializer already implemented take care of this?

Thank you before hand.

**Comment by knaeckeKami** [comment]
> mutationQueueBox.add(serializers.serialize(request));

There is a lot going on this line, and with no stacktrace I can only guess what the actual problem is.

Does hive throw the error or the serializer? Do you have custom scalars in your schema that are JSON maps?

**Comment by francescreig** [comment]
Hello again, thank you for your quick response.
The error is thrown by the the serializer (I guess) and yes I have custom scalars that are JSON maps that I serialize with the `JsonObject`. 
A part from that, the requests are being sent correctly when I do not use the OfflineMutationTypedLink, but I am not sure what happens on this line. Does JsonObject not serialize `Map<String, dynamic>`?

**Comment by knaeckeKami** [comment]
try adding 

`     type_overrides:` also in the serializer_builder

**Comment by francescreig** [comment]
So I have tried to add `type_overrides` on the serializer_builder like this:

```yaml
targets:
  $default:
    builders:
      ferry_generator|graphql_builder:
        enabled: true
        options:
          schema: path/to/schema.graphql
          type_overrides:
            ObservationDataScalar:
              name: JsonObject
              import: "package:built_value/json_object.dart"

      ferry_generator|serializer_builder:
        enabled: true
        options:
          schema: path/to/schema.graphql
          custom_serializers:
            - import: "package:built_value/src/json_object_serializer.dart"
              name: JsonObjectSerializer
          type_overrides:
            ObservationDataScalar:
              name: JsonObject
              import: "package:built_value/json_object.dart"
```
but I still get the same error. Am I defining wrong the type_overrides on the serializer_builder?
