### ISSUE TITLE
How to add multiple schema.graphql files?

### ISSUE THREAD

**Issue by danielRi** [gql-dart/ferry#510]
Hi,

I want to play around with ferry a little bit and want to add two different schema files. However I cant generate the ferry classes when I run the build_runner

File structure:

<img width="210" alt="Bildschirm­foto 2023-04-18 um 09 59 50" src="https://user-images.githubusercontent.com/3048681/232711615-254098fa-87fe-45c8-9df7-efa5813da130.png">

And this is my `build.yaml`

```
targets:
  $default:
    builders:
      ferry_generator|graphql_builder:
        generate_for:
          - lib/graphql/countries/**
        enabled: true
        options:
          schema: blocbloc|lib/graphql/countries/schema.graphql
          output_dir: 'graphql_generated'
          when_extensions:
            when: true
            maybeWhen: true
      ferry_generator|serializer_builder:
        enabled: true
        options:
          schema: blocbloc|lib/graphql/countries/schema.graphql
          output_dir: 'graphql_generated'
          when_extensions:
            when: true
            maybeWhen: true
  movieapi:
    builders:
      ferry_generator|graphql_builder:
        generate_for:
          - lib/graphql/movies/**
        enabled: true
        options:
          schema: blocbloc|lib/graphql/movies/schema.graphql
          output_dir: 'generated'
          when_extensions:
            when: true
            maybeWhen: true
      ferry_generator|serializer_builder:
        enabled: true
        options:
          schema: blocbloc|lib/graphql/movies/schema.graphql
          output_dir: 'generated'
          when_extensions:
            when: true
            maybeWhen: true

```

If I do a 

`flutter pub run build_runner build --delete-conflicting-outputs `

I always get the following error:

```Both built_value_generator:built_value and built_value_generator:built_value may output lib/client_injector.built_value.g.part. Potential outputs must be unique across all builders. See https://github.com/dart-lang/build/blob/master/docs/faq.md#why-do-builders-need-unique-outputs
```
The file is just a dart file that does nothing, its under /lib

What am I doing wrong?
