### ISSUE TITLE
Missing scalar JSON. Defaulting to String

### ISSUE THREAD

**Issue by LatVAlY** [gql-dart/ferry#516]
hello everyone,
I after spending 2 days on this, and trying every solution I found out there, couldn't resolve this issue, I would appreciate if you can help me out with this.

using dep:
ferry_generator: ^0.8.0+1
json_serializable: ^6.5.4
freezed: ^2.2.0
graphql_codegen: ^0.12.0

my query: 
```
scalar JSON

type Filters {
    categoryId: Int
    id: Int
    name: String
    type: String
    values: [JSON!]!
}

query getFilters {
    getFilters {
        Filters {
            type
            id
            categoryId
            name
            values # is a simple Map<String, dynamic>
        }
    }
}
```
build.yaml

```
targets:
  $default:
    builders:
      gql_build|schema_builder:
        enabled: true
        options:
          type_overrides:
            JSON:
              name: JsonObject
              import: "package:built_value/json_object.dart"
      gql_build|ast_builder:
        enabled: true
      gql_build|data_builder:
        enabled: true
        options:
          schema: startup_namer|lib/graphql-schema/schema/schema.graphql
          type_overrides:
            JSON:
              name: JsonObject
              import: "package:built_value/json_object.dart"
      gql_build|var_builder:
        enabled: true
        options:
          schema: startup_namer|lib/graphql-schema/schema/schema.graphql
          type_overrides:
            JSON:
              name: JsonObject
              import: "package:built_value/json_object.dart"
      gql_build|serializer_builder:
        enabled: true
        options:
          schema: startup_namer|lib/graphql-schema/schema/schema.graphql
          custom_serializers:
            - import: "package:built_value/src/json_object_serializer.dart"
              name: JsonObjectSerializer

      ferry_generator|req_builder:
        enabled: true
        options:
          schema: startup_namer|lib/graphql-schema/schema/schema.graphql
          type_overrides:
            JSON:
              name: JsonObject
              import: "package:built_value/json_object.dart"


```
error occurs:

Missing scalar JSON. Defaulting to String

I also tried it with this:

build.yaml 
```
targets:
  $default:
    builders:
      ferry_generator|serializer_builder:
        enabled: true
        options:
          schema: startup_namer|lib/graphql-schema/schema/schema.graphql
          custom_serializers:
            - import: 'package:startup_namer/json_serializer.dart'
              name: JsonTypeSerializer

      ferry_generator|graphql_builder:
        enabled: true
        options:
          schema: startup_namer|lib/graphql-schema/schema/schema.graphql
          type_overrides:
            JSON:
              name: Map<String, dynamic>

```

and json_serializer.dart 

```
import "package:built_value/serializer.dart";
import "package:gql/language.dart";
import "package:gql_exec/gql_exec.dart";
import 'package:built_collection/built_collection.dart';
import "package:gql_code_builder/src/serializers/json_serializer.dart";

class JsonTypeSerializer implements PrimitiveSerializer<BuiltMap<String, dynamic>> {
  @override
  BuiltMap<String, dynamic> deserialize(
      Serializers serializers,
      Object serialized, {
        FullType specifiedType = FullType.unspecified,
      }) {
    assert(serialized is String,
    "JsonTypeSerializer expected 'String' but got ${serialized.runtimeType}");
    return BuiltMap<String, dynamic>.from(serialized as Map);
  }

  @override
  Object serialize(
      Serializers serializers,
      BuiltMap<String, dynamic> abdel, {
        FullType specifiedType = FullType.unspecified,
      }) =>
      abdel.toString();

  @override
  Iterable<Type> get types => [Map];

  @override
  String get wireName => "Abdel";
}

// class BuiltMapJsonSerializer extends JsonSerializer<BuiltMap<String, dynamic>> {
//   @override
//   BuiltMap<String, dynamic> fromJson(Map<String, dynamic> json) {
//     print('MyJsonSerializer fromJson: $json');
//     return BuiltMap.of(json);
//   }
//
//   @override
//   Map<String, dynamic> toJson(BuiltMap<String, dynamic> operation) {
//     print('MyJsonSerializer toJson: ${operation.toString()}');
//     return operation.asMap();
//   }
// }

class OperationSerializer extends JsonSerializer<Operation> {
  @override
  Operation fromJson(Map<String, dynamic> json) => Operation(
    document: parseString(json["document"] as String),
    operationName: json["Abdel"] as String,
  );

  @override
  Map<String, dynamic> toJson(Operation operation) => <String, dynamic>{
    "document": printNode(operation.document),
    if (operation.operationName != null)
      "operationName": operation.operationName,
  };
}
```
and got the same issue

**Comment by knaeckeKami** [comment]
your first example uses the old build.yaml syntax. 
the latter one is correct, but is missing the type_overrides in the serializer_builder. 

another user managed to get this working here: https://github.com/gql-dart/ferry/issues/493#issuecomment-1443555107

**Comment by LatVAlY** [comment]
update, I also tried that solution 
here is my current build.yaml
```
targets:
  $default:
    builders:
      ferry_generator|graphql_builder:
        enabled: true
        options:
          schema: startup_namer|lib/graphql-schema/schema/schema.graphql
          when_extensions:
            when: true
            maybeWhen: true
          type_overrides:
            JSON:
              name: Map<String, dynamic>
              import: 'package:metadata_serializer.dart'
      ferry_generator|serializer_builder:
        enabled: true
        options:
          schema: startup_namer|lib/graphql-schema/schema/schema.graphql
          when_extensions:
            when: true
            maybeWhen: true
          type_overrides:
            JSON:
              name: Map<String, dynamic>
              import: "package:metadata_serializer.dart"
          custom_serializers:
            - import: 'package:metadata_serializer.dart'
              name: GenericScalarSerializer
              
```

and metadata_serializer.dart
```
import 'package:built_value/serializer.dart';
import "package:gql_code_builder/src/serializers/json_serializer.dart";


class GenericScalarSerializer extends JsonSerializer<Map<String, dynamic>> {
  @override
  Iterable<Type> get types => [Map<String, dynamic>];

  @override
  String get wireName => 'JSON';

}
```
this didn't work

**Comment by knaeckeKami** [comment]
you don't need an import for Map<String,dynamic>

**Comment by LatVAlY** [comment]
```
targets:
  $default:
    builders:
      ferry_generator|graphql_builder:
        enabled: true
        options:
          schema: startup_namer|lib/graphql-schema/schema/schema.graphql
          when_extensions:
            when: true
            maybeWhen: true
          type_overrides:
            JSON:
              name: Map<String, dynamic>
      ferry_generator|serializer_builder:
        enabled: true
        options:
          schema: startup_namer|lib/graphql-schema/schema/schema.graphql
          when_extensions:
            when: true
            maybeWhen: true
          custom_serializers:
            - import: 'package:metadata_serializer.dart'
              name: GenericScalarSerializer
          type_overrides:
            JSON:
              name: Map<String, dynamic>
```

:( same error
