### ISSUE TITLE
[FerryGenerator] Why isn't my basic schema working?

### ISSUE THREAD

**Issue by Knaackee** [gql-dart/ferry#538]
I am new to ferry. Thanks for the great work!

I just created a demo project to test ferry and stumbled upon a problem. 

I Used this basic schema. 

## schema.graphql
```graphql
type Todo {
  text: String!
}

type Query {
  todos: [Todo]
}

input TodoInput {
  text: String!
}

type Mutation {
  createTodo(input: TodoInput): Todo
}
```

### todos.graphql

```graphql
query Todo {
  todos {
    text
  }
}
```

### createTodo.graphql

```graphql
mutation CreateTodo($input: TodoInput) {
  createTodo(input: $input) {
    text
  }
}
```
## build.yaml
```yaml
targets:
  $default:
    builders:
      ferry_generator|graphql_builder:
        generate_for:
          - lib/graphql/queries/**
        enabled: true
        options:
          schema: myProject|lib/graphql/schema.graphql
      ferry_generator|serializer_builder:
        enabled: true
        options:
          schema: myProject|lib/graphql/schema.graphql
```

### Running `dart run build_runner build --delete-conflicting-outputs` results in:

```
[SEVERE] built_value_generator:built_value on lib/graphql/queries/__generated__/createTodo.var.gql.dart:
Error in BuiltValueGenerator for abstract class GCreateTodoVars implements Built<GCreateTodoVars, InvalidType>.
Please make the following changes to use BuiltValue:

1. Make field input have non-dynamic type. If you are already specifying a type, please make sure the type is correctly imported.
```

I searched a lot but didn't find a solution. 

E.g. I imported the `schema.graphql` into my query, but nothing changed.

Thanks again!
