### ISSUE TITLE
failed due to: Deserializing to

### ISSUE THREAD

**Issue by minhnguyenandpad** [gql-dart/ferry#561]
Here the scenario:
When my BE team return an api with new status api but haven't released the schema yet. Then when I called Api. This error showed up. 

`failed due to: Deserializing to 'CAR_STATUS' failed due to: Invalid argument(s): BROKEN, #0      BuiltJsonSerializers._deserialize `

Is there any way to handle them to avoid such bugs? This make my app crash.

Here is my setup

```yaml
targets:
  $default:
    builders:
      ferry_generator|graphql_builder:
        enabled: true
        options:
          schema: my_car|lib/data/graphql/schema.graphql

      ferry_generator|serializer_builder:
        enabled: true
        options:
          schema: my_car|lib/data/graphql/schema.graphql
```
