### ISSUE TITLE
Custom ISO serializer for DateTime

### ISSUE THREAD

**Issue by Inlustra** [gql-dart/ferry#572]
Hi, we're currently trying to parse a date time in ISO format. 
On the server the scalar name is `DateTime`

build.yaml
```
targets:
  $default:
    builders:
      ferry_generator|graphql_builder:
        enabled: true
        options:
          schema: package:my_app|lib/schema.graphql
          type_overrides:
            EmailAddress:
              name: String
            DateTime: 
              name: DateTime
          custom_serializers:
            - import: "package:my_app|lib/utils/date_time_deserializer.dart"
              name: DateTimeSerializer
              
      ferry_generator|serializer_builder:
        enabled: true
        options:
          schema: driver_app|lib/schema.graphql
          type_overrides:
            DateTime:
              name: DateTime
```

Unfortunately our date_time_serializer never gets used, could anyone lend some support?
