### ISSUE TITLE
Cannot build library using `ferry` 0.16.1

### ISSUE THREAD

**Issue by rneswold** [gql-dart/ferry#636]
We have a library that uses `ferry`. An app of ours uses the library but no longer builds due to dependency issues. Our library uses subscriptions and, in trying to use the latest `ferry` versions, we're not able to build because of version conflicts. A portion of our `pubspec.yaml` dependencies:

```yaml
    ferry: ^0.16.1
    gql_http_link: ^1.1.0
    gql_websocket_link: ^2.0.1
    gql_code_builder: ^0.13.0
```

`ferry` v0.16.1 pulls in `web_socket_channel` v3.0.2. For WebSockets, your documentation recommends `gql_websocket_link` for non-Apollo applications. Unfortunately, `web_socket_channel` v3.0 wants `rxdart` v0.28 whereas `gql_websocket_link` wants `rxdart` < v0.28.

Does `ferry` v0.16.1 recommend a different WebSocket package? Does anyone have a set of dependencies to get subscriptions working with the latest `ferry`?

(We'd stay at the previous version, but a different package the app uses already wants `rxdart` v0.28, so we thought we'd take the opportunity to update `ferry`.)

Thanks for any help you can provide!
