### ISSUE TITLE
custom scalars error

### ISSUE THREAD

**Issue by TomVista** [gql-dart/ferry#89]
## build
```
targets:
  $default:
    builders:
      gql_build|schema_builder:
        enabled: true
        options:
          type_overrides:
            jsonb:
              name: DateTime
            timestamp:
              name: DateTime  
      gql_build|ast_builder:
        enabled: true
      gql_build|data_builder:
        enabled: true
        options:
          schema: app|lib/schema.graphql
      gql_build|var_builder:
        enabled: true
        options:
          schema: app|lib/schema.graphql
      gql_build|serializer_builder:
        enabled: true
        options:
          schema: app|lib/schema.graphql

      ferry_generator|req_builder:
        enabled: true
        options:
          schema: app|lib/schema.graphql
```

## error message
```
Error in BuiltValueGenerator for abstract class Ginsert_missionVars implements Built<Ginsert_missionVars, dynamic>.
Please make the following changes to use BuiltValue:

1. Make field end_time have non-dynamic type. If you are already specifying a type, please make sure the type is correctly imported.
```

**Comment by TomVista** [comment]
maybe not have Serializer:dog

**Comment by TomVista** [comment]
```
targets:
  $default:
    builders:
      gql_build|schema_builder:
        enabled: true
        options:
          type_overrides:
            jsonb:
              name: String
            timestamp:
              name: String  
      gql_build|ast_builder:
        enabled: true
      gql_build|data_builder:
        enabled: true
        options:
          schema: app|lib/schema.graphql
      gql_build|var_builder:
        enabled: true
        options:
          schema: app|lib/schema.graphql
      gql_build|serializer_builder:
        enabled: true
        options:
          schema: app|lib/schema.graphql
          jsonb:
            import: 'app|lib/ferrySerializer/jsonbSerializer.dart'
            name: jsonbSerializer
          timestamp:
            import: 'app|lib/ferrySerializer/jsonbSerializer.dart'
            name: jsonbSerializer

      ferry_generator|req_builder:
        enabled: true
        options:
          schema: app|lib/schema.graphql
```
// Serializer
```
import 'package:built_value/serializer.dart';

class jsonbSerializer implements PrimitiveSerializer<String> {
  @override
  String deserialize(Serializers serializers, Object serialized, {FullType specifiedType = FullType.unspecified}) {
    return serialized;
  }

  @override
  Object serialize(Serializers serializerstring, String jsonb, {dynamic specifiedType = FullType.unspecified}) {
    return jsonb;
  }

  @override
  // TODO: implement types
  Iterable<Type> get types => [String];

  @override
  // TODO: implement wireName
  String get wireName => 'jsonbSerializer';
}

```
