### ISSUE TITLE
Can you override the default `DateTime` serializer?

### ISSUE THREAD

**Issue by danielmahon** [gql-dart/ferry#91]
Loving the library so far but I have a couple questions...

I got the rest of my schema working properly, along with other custom scalars, but `DateTime` still seems to default to using the default serializer which only returns a string, and its also converting it to `GDateTime`. If I include a custom `DateTimeSerializer` it ignores it. Is there a better way to ensure it gets properly deserialized into a proper `DateTime` object? I'm pulling in a Prisma schema FYI.

```dart
abstract class GDateTime implements Built<GDateTime, GDateTimeBuilder> {
  GDateTime._();

  factory GDateTime([String value]) =>
      _$GDateTime((b) => value != null ? (b..value = value) : b);

  String get value;
  @BuiltValueSerializer(custom: true)
  static Serializer<GDateTime> get serializer =>
      _i1.DefaultScalarSerializer<GDateTime>(
          (Object serialized) => GDateTime(serialized));
}
```

```dart
import 'package:built_value/serializer.dart';

class DateTimeSerializer implements PrimitiveSerializer<DateTime> {
  @override
  DateTime deserialize(
    Serializers serializers,
    Object serialized, {
    FullType specifiedType = FullType.unspecified,
  }) {
    assert(serialized is String,
        "DateSerializer expected 'String' but got ${serialized.runtimeType}");
    return DateTime.parse(serialized.toString());
  }

  @override
  Object serialize(
    Serializers serializers,
    DateTime date, {
    FullType specifiedType = FullType.unspecified,
  }) =>
      date.toIso8601String();

  @override
  Iterable<Type> get types => [DateTime];

  @override
  String get wireName => 'DateTime';
}
```

**Comment by friebetill** [comment]
I have the same setup and the translation in `DateTime` works fine for me. What does your build.yaml look like?

Mine looks like this:
```yaml
targets:
  $default:
    builders:
      gql_build|schema_builder:
        enabled: true
        generate_for:
          - lib/graphql/**
        options:
          type_overrides:
              DateTime:
                name: DateTime
      gql_build|ast_builder:
        enabled: true
        generate_for:
          - lib/graphql/**
      gql_build|serializer_builder:
        enabled: true
        options:
          schema: client|lib/graphql/schema.graphql
          custom_serializers:
          - import: 'package:client/graphql/date_time_serializer.dart'
            name: DateTimeSerializer
      gql_build|data_builder:
        enabled: true
        generate_for:
          - lib/graphql/**
        options:
          schema: client|lib/graphql/schema.graphql
          type_overrides:
            DateTime:
              name: DateTime
      gql_build|var_builder:
        enabled: true
        generate_for:
          - lib/graphql/**
        options:
          schema: client|lib/graphql/schema.graphql
          type_overrides:
            DateTime:
              name: DateTime

      ferry_generator|req_builder:
        enabled: true
        generate_for:
          - lib/graphql/**
        options:
          schema: client|lib/graphql/schema.graphql
          type_overrides:
            DateTime:
              name: DateTime
```
