### ISSUE TITLE
How to convert custom scalar to List/BuiltList<Model>?

### ISSUE THREAD

**Issue by danielmahon** [gql-dart/ferry#92]
I can't seem to figure out how to convert a custom scalar to a `List` or `BuiltList` of a local model.

```yaml
type_overrides:
  DateTime:
    name: DateTime
  MyModels:
    name: BuiltList<MyModel>
    # import: 'package:name/path/to/model.dart'
```

Ive implemented a `MyModelsSerializer` which returns `BuiltList<MyModel>`. Ive also tried importing the model file that. defines `MyModel` (a freezed class)

It doesn't seem to resolve the types properly so `build_runner` keeps throwing `Make field [name] have non-dynamic type. Is there a naming convention I'm missing for the config?
